apiVersion: v1
kind: Service
metadata:
  name: cluster-almond-external-service
  labels:
    app: cluster-almond-external-service
    service: cluster-almond-external-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: cluster-almond-external-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-almond-external-service
  labels:
    account: cluster-almond-external-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-almond-external-service
  labels:
    app: cluster-almond-external-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-almond-external-service
  template:
    metadata:
      labels:
        app: cluster-almond-external-service
    spec:
      serviceAccountName: cluster-almond-external-service
      containers:
      - name: external-fibonacci-go
        image: 192.168.4.14:443/fork/fibonacci-go:v1
        #image: 192.168.4.14:443/fork/fibonacci-py:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: PORT
          value: "8000"
        ports:
        - containerPort: 8000
