apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-serviceexport-binding
subjects:
  - kind: ServiceAccount
    name: operator-controller-manager
    namespace: fork-system
roleRef:
  kind: ClusterRole
  name: operator-serviceexport-role
  apiGroup: rbac.authorization.k8s.io
