apiVersion: v1
kind: Service
metadata:
  name: cluster-cherry-external-proxy
  labels:
    app: cluster-cherry-external-proxy
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    name: cluster-cherry-external-proxy
    targetPort: 8000
    nodePort: 31554
  selector:
    app: cluster-cherry-external-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-cherry-external-proxy
  labels:
    app: cluster-cherry-external-proxy
spec:
  selector:
    matchLabels:
      app: cluster-cherry-external-proxy
  template:
    metadata:
      labels:
        app: cluster-cherry-external-proxy
    spec:
      containers:
      - name: cluster-cherry-external-proxy
        image: 192.168.4.14:443/fork/proxy:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: FIBONACCI_HOSTNAME
            value: "cluster-almond-external-service.default.svc.clusterset.local"
          - name: FIBONACCI_PORT
            value: "8000"
          - name: PORT
            value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-cherry-internal-proxy
  labels:
    app: cluster-cherry-internal-proxy
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    name: cluster-cherry-internal-proxy
    targetPort: 8000
    nodePort: 31555
  selector:
    app: cluster-cherry-internal-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-cherry-internal-proxy
  labels:
    app: cluster-cherry-internal-proxy
spec:
  selector:
    matchLabels:
      app: cluster-cherry-internal-proxy
  template:
    metadata:
      labels:
        app: cluster-cherry-internal-proxy
    spec:
      containers:
      - name: cluster-cherry-internal-proxy
        image: 192.168.4.14:443/fork/proxy:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          - name: FIBONACCI_HOSTNAME
            value: "cluster-cherry-internal-service"
            #value: "moving-service.default.svc.clusterset.local"
            #value: "moving-service.default.svc.cluster.local"
          - name: FIBONACCI_PORT
            value: "8000"
          - name: PORT
            value: "8000"
